common: &common
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>

production:
  <<: *common

staging:
  <<: *common

test: &test
  <<: *common
  database: <%= ENV['DB_TEST_NAME'] %>

development:
  <<: *common